### ISSUE TITLE
Hey there :)

### ISSUE THREAD

**Issue by wladston** [treddeni/ripple-bot#1]
I'd love to use and contribute to your bot. I got it running here, but I have no idea how to operate it, what the buttons do, etc.

How about writing some documentation that explains how to:
1. Install (npm install, and npm install ripple-lib, …)
2. configure (edit the /config file in such and such ways…)
3. run (node app [config file] [http port]
4. understand what the interface does (I could not :see_no_evil: )

**Comment by treddeni** [comment]
I added some description to the readme.  Probably not everything you want, but hopefully it helps.  I haven't used the bot in several months, so I'm not sure how well it's currently working.  I'd recommend running with makeTrades set to false in the config file, until you understand it better and are happy with the trades you see it simulating.

**Comment by wladston** [comment]
Thanks :)
